x-common: &default-config
  env_file:
    - .env
  restart: on-failure
  networks:
    - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/${USER}/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/${USER}/data/mariadb'

secrets:
  mariadb_user:
    file: ../secrets/mariadb_user.txt
  mariadb_root_pass:
    file: ../secrets/mariadb_root_pass.txt
  mariadb_pass:
    file: ../secrets/mariadb_pass.txt
  wp_admin:
    file: ../secrets/wp_admin.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt

services:
  mariadb:
    <<: *default-config
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - mariadb_user
      - mariadb_root_pass
      - mariadb_pass
  
  nginx:
    <<: *default-config
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      # - "8080:8080"
  
  wordpress:
    <<: *default-config
    container_name: wordpress
    image: wordpress
    volumes:
    - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    secrets:
      - mariadb_user
      - mariadb_pass
      - wp_admin
      - wp_admin_pass
      - wp_user
      - wp_user_pass
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge