version: '3.9'
 
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb

  wordpress:
    container_name: wp-php
    build: ./requirements/wordpress
    volumes:
      - ./web:/var/www/html

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html

