version: '3.9'

services:
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_files:/var/www/html
    networks:
      - wp_network
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs
    networks:
      - wp_network
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - wp_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp

networks:
  project:
    driver: bridge

