FROM debian:bullseye

RUN apt-get update && apt-get install -y \
	mariadb-server -y && \
	rm -rf /var/lib/apt/lists/*

RUN rm /etc/mysql/mariadb.conf.d/50-server.cnf
COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d

CMD ["mysqld_safe"]