services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    secrets:
      - db_user
      - db_root_password
      - db_password
    restart: on-failure
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: wordpress

  wordpress:
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    secrets:
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_user
      - wp_user_password
    restart: on-failure
    depends_on:
      - mariadb
    expose:
      - "8443"
    ports:
      - "8443:443"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/db_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
      WP_ADMIN_USER_FILE: /run/secrets/wp_admin_user
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_FILE: /run/secrets/wp_user
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/ksansom/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/ksansom/data/mariadb'

networks:
  inception:
    driver: bridge

